site_name: test-annotations

theme:
  name: material
  features:
    - content.code.annotate  

plugins: 
 - techdocs-core

# hooks:
# - hooks.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - home: index.md
